name: Deploy API and React App to Azure - webhook-receiver-p

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the React frontend
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React Frontend
        working-directory: ./frontend
        run: npm run build

      # Move the frontend build to the backend directory
      - name: Move Frontend Build to Backend
        run: mv ./frontend/build ./backend/build

      # Set up Node.js version for backend
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Build Backend
        working-directory: ./backend
        run: npm run build --if-present

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7626AF83F7A846EC8DCAD4D50E442ECB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1D67AB48B85C4DF7A398E571B6344E1F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC955CF840A04BEF80F1A63054B24CF0 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webhook-receiver-p'
          slot-name: 'Production'
          package: .